sudo: false
language: java
notifications:
  email: false
  pushover:
    on_failure: always
    on_success: change
    api_key:
      secure: 4Tc+kW54GNdcCVHsy/62sSMxstMLehN2ST2lV7FlMMSrnoeIcRWzcKBJ/or4sYOF9fS+F64+yiQ15Ob05vdovE7qBesJ6rs2Gl+skSsuZtaMpAtGh9ztTFF/itvKV9cErqxfG3OIXr3rUtAFJg8A2iO7B4++WWhtwynTeo4AhmU5NwCKa2e8PtBSKZo1UPysqQEX6tHjtSBIbOLXJDAul62ngB7jZu2VEzFpdLkQYlzSDga2kBqGRtL+rqc2ecQ7dOYDyCIIsKBTEiTbfGRb+oB2sBB2OGxAarfWaCsukAT43ofLlGuszT5H/e83Lh3ZkSxOP8CJrJ9POhBxb/83uCHgSsmFvyr2kwCJL7Lc13Go48qIc7oB9ueIxaY+m+b0NG+VsXy+sgfDcZRj2gS3SPPKO3Pi1rYUr4vuiuGOTMg0YKqSwz/iBtYB95aR35Quf7AeqAPV9+hRFqEdPCs5j8kaM0EvvyK6qwGGGeaaYKbGi4k6ghvCGqUtiG18M5ldEsonKfAvaNpGFF24SSU3JZ1NE2DJ0M50MaOSGOV9ND5iZNL4lmcld7XQ73gKn1jxGrZ9eYegZk8TQYmxDopMA9jm2LJ7to2Om8CJRJyhb1nz5KlORCkNh2uvm8BpbYtSyZZ+PkIt4AZL5CEPeAD440QI78KxeaFUwpxYWUQ6DNM=
    users:
      - secure: vWZJqTTM+dMGZzgHvUY2uwGY4Wj984esRpUMkbu2fMydBkSUwMVVfe4g5PZPUDCO9GrSWglzL9t9pXChFrcM4e3bBLTm+pmZ5p6UIEEFpS+QNle+X/cPBqGva85cyAaPTARQCxS1sJra3RPAeU6GVQvN3i9RhZTKFrWU/yx1E1yol+TI9fCf6N6KzL/RkPzVDM2pWw4x/SHvUChpeA2Kb5XwQP+XNU+W9Sv58qD1IY6+2SaXvxt2MSpjGFI6rREDdEVd+dh+rUafwF2sKwZXQpq775gm1XaSz881jiMSWci4JPjKQ/QjvluR25kpE+JOjp4337nVRn6jAxCgN7qgd8V+3zrCQJ5W+c9HCZWNQQgAfy58ryGG1kZGUUpdwhocijPOCrpsmEdSSIV3XN+jxRTcNpgVtLQp/3Q6MfOBTWsXRtsLYYXnYvBfjvhgAkwDXKIe/+UIlaUvRxcnG3rFbfeClDspOQ0ecqAzJ+XNHMWZ3cNwHL/V+9RI3PpR2mqfA0A8F5ZWpz+tVPvPos3LYCeCm6okEIeC/m5sq96ZTICkAMeuHq+5xwMfhf101rgmkOFmPbpe7i5SUbBlpygfOpV0myT4lb09oO9BSHdDfCmkOmxe+Q0P6/UuNkMJWTp5d1riOyDr2u7WsBtCi1OrBS2mVhUQrybugNfXtj2qd/k=
jdk:
  - oraclejdk8
install:
  - wget --quiet --output-document=/tmp/ceylon.zip $CEYLON
  - unzip -q /tmp/ceylon.zip
  - export PATH=$PATH:$PWD/ceylon-1.3.2/bin/
  - export CEYLON_HOME=$PWD/ceylon-1.3.2
script:
  - cd server
  - ceylon compile
env:
  global:
    - CEYLON="http://ceylon-lang.org/download/dist/1_3_2"

